# Generated by Django 5.1.6 on 2025-03-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_document_status_alter_document_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новый"),
                    ("in_progress", "В работе"),
                    ("approved", "Подтвержден"),
                    ("rejected", "Отказ"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
