# Generated by Django 5.1.6 on 2025-03-24 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_customuser_private_key_customuser_public_key_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="documentsignature",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="public_key",
        ),
        migrations.AddField(
            model_name="documentsignature",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="documentsignature",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificate_file", models.BinaryField()),
                ("private_key_file", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="documentsignature",
            name="signed_at",
        ),
        migrations.RemoveField(
            model_name="documentsignature",
            name="signer",
        ),
    ]
