# Generated by Django 5.1.6 on 2025-04-16 10:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_documentversion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentsignature",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentsignature",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="documentversion",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documenttransferhistory",
            name="document_version",
        ),
        migrations.CreateModel(
            name="DocumentVersionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_id", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("etag", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_history",
                        to="webapp.document",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Certificate",
        ),
        migrations.DeleteModel(
            name="DocumentSignature",
        ),
        migrations.DeleteModel(
            name="DocumentVersion",
        ),
    ]
