# Generated by Django 5.1.6 on 2025-06-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_documentversionhistory_version_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversionhistory",
            name="is_signed",
            field=models.BooleanField(default=False, verbose_name="Подписан"),
        ),
        migrations.AddField(
            model_name="documentversionhistory",
            name="signature_placeholder",
            field=models.TextField(
                blank=True, null=True, verbose_name="Заглушка подписи"
            ),
        ),
    ]
