# Generated by Django 5.1.6 on 2025-06-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0013_alter_documenttransferhistory_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversionhistory",
            name="file_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documenttransferhistory",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("transfer", "Transfer"),
                    ("version_upload", "Version Upload"),
                    ("signature", "Signature"),
                    ("upload", "Upload"),
                ],
                default="transfer",
                max_length=20,
            ),
        ),
    ]
