# Generated by Django 5.1.6 on 2025-06-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0014_documentversionhistory_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversionhistory",
            name="certificate_thumbprint",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Thumbprint сертификата",
            ),
        ),
        migrations.AddField(
            model_name="documentversionhistory",
            name="signature_file_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Имя файла подписи (p7s)",
            ),
        ),
        migrations.AddField(
            model_name="documentversionhistory",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время подписи"
            ),
        ),
    ]
