# Generated by Django 5.1.6 on 2025-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_documentversionhistory_certificate_thumbprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversionhistory",
            name="signature_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
